In [2]:
price=[4,8,3,6,4,11,3]
print(price * 2.5)

TypeError: can't multiply sequence by non-int of type 'float'

In [7]:
import numpy as np
npPrice = np.array(price)
type(npPrice)

numpy.ndarray

In [6]:
print(npPrice * 2.5)

[10.  20.   7.5 15.  10.  27.5  7.5]


In [20]:
npTax = np.array([1,1,2,1,1,2,2])
print(npPrice*npTax)

[ 4  8  6  6  4 22  6]


In [13]:
test=np.array([1.0, 2, 3.5, 0.2, False])
print(test)

[1.  2.  3.5 0.2 0. ]


In [14]:
test=np.array((1.0, 2, 3.5, 0.2))
print(test)

[1.  2.  3.5 0.2]


In [17]:
npFinal = npPrice * (npTax * 18)
print(npFinal)

[ 72 144 108 108  72 396 108]


In [18]:
npFinal = npPrice * (npTax * 18)
print(npFinal)

[ 72 144 108 108  72 396 108]


In [21]:
npFinal > 100

array([False,  True,  True,  True, False,  True,  True])

In [22]:
[npFinal > 100]

[array([False,  True,  True,  True, False,  True,  True])]

In [25]:
ifValid = npFinal > 100
print(ifValid)

[False  True  True  True False  True  True]


In [43]:
npFilter = npFinal[npFinal > 100]
print(npFilter)

[144 108 108 396 108]


In [41]:
sample = [1,2,3,5,4,6,7,8,5,3,2]
print(sample[::-2])
print(sample[2:-3])
print(sample[ : : -2])

[2, 5, 7, 4, 3, 1]
[3, 5, 4, 6, 7, 8]
[2, 5, 7, 4, 3, 1]
